"""empty message

Revision ID: e399af683d41
Revises: 
Create Date: 2026-02-11 22:31:17.948591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e399af683d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('specialties', sa.Enum('CARDIOLOGY', 'DERMATOLOGY', 'PEDIATRICS', 'GENERAL_PRACTICE', 'NEUROLOGY', 'PSYCHOLOGY', 'ORTHOPEDICS', 'GASTROENTEROLOGY', name='specialtytype'), nullable=False),
    sa.Column('biography', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_expires', sa.DateTime(), nullable=True),
    sa.Column('cal_link', sa.String(length=200), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('pacient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_expires', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pacient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('cal_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'pending', name='statusappointment'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['pacient_id'], ['pacient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id_doctor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.drop_table('appointments')
    op.drop_table('pacient')
    op.drop_table('doctors')
    # ### end Alembic commands ###
